# Generated by Django 4.2.3 on 2023-07-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('HARDWARE', 'Hardware'), ('ART SUPPLIES', 'Art Supplies'), ('OTHER', 'Other')], default='', max_length=50)),
            ],
        ),
    ]
