# Generated by Django 4.2.3 on 2023-08-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='min_amount',
        ),
    ]
