# Generated by Django 4.2.3 on 2023-07-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suppliesNeeded',
        ),
    ]
