# Generated by Django 4.2.3 on 2023-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_amount',
            field=models.IntegerField(default=5),
        ),
    ]
