# Generated by Django 4.2.3 on 2023-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HW', 'Hardware'), ('AS', 'Art Supplies'), ('O', 'Other')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created',
            new_name='updated',
        ),
    ]
