# Generated by Django 4.2.3 on 2023-07-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_code',
        ),
    ]
