# Generated by Django 4.2.3 on 2023-07-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categories_rename_created_item_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HW', 'Hardware'), ('AS', 'Art Supplies'), ('O', 'Other')], default='', max_length=50),
        ),
    ]
