# Generated by Django 4.2.3 on 2023-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categories_remove_item_category_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_code',
            field=models.CharField(default='TLS', max_length=100),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_name',
            field=models.CharField(default='Tools', max_length=100),
        ),
    ]
