# Generated by Django 4.2.5 on 2023-09-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_log_backroom_quantity_log_makerspace_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log_id',
        ),
    ]
