# Generated by Django 4.2.3 on 2023-11-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_log_log_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(choices=[('BX', 'Box'), ('EA', 'Each'), ('ST', 'Set'), ('PK', 'Pack/100'), ('DZ', 'Dozen')], default=None, max_length=100)),
                ('unit_name', models.CharField(choices=[('BX', 'Box'), ('EA', 'Each'), ('ST', 'Set'), ('PK', 'Pack/100'), ('DZ', 'Dozen')], default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsUnit', to='inventory.unit'),
        ),
    ]
