# Generated by Django 4.2.3 on 2023-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_log_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dateTime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
