# Generated by Django 4.2.3 on 2023-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
