# Generated by Django 4.2.3 on 2023-12-05 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_log_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
