# Generated by Django 4.2.3 on 2023-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vendor_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
