# Generated by Django 4.2.3 on 2023-12-05 15:51

from django.db import migrations
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_log_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=inventory.models.AutoDateTimeField(auto_now_add=True),
        ),
    ]
