# Generated by Django 4.2.3 on 2023-12-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_log_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='dateTime',
        ),
    ]
