# Generated by Django 4.2.3 on 2023-12-05 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_log_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
