# Generated by Django 4.2.3 on 2023-12-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_log_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='change',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
