# Generated by Django 4.2.3 on 2024-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_category_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='vendor',
            field=models.CharField(choices=[('DOE', 'ShopDOE'), ('AMZ', 'Amazon'), ('BLICK', 'Blick'), ('HD', 'Home Depot'), ('Fl', 'Form Labs'), ('BL', 'Bambu Lab'), ('HL', 'Hobby Lobby'), ('FAST', 'Fastenal'), ('GLCRFT', 'Glass Crafters'), ('MIC', 'Michaels'), ('ADO', 'Adorama')], default='DOE', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(choices=[('DOE', 'ShopDOE'), ('AMZ', 'Amazon'), ('BLICK', 'Blick'), ('HD', 'Home Depot'), ('Fl', 'Form Labs'), ('BL', 'Bambu Lab'), ('HL', 'Hobby Lobby'), ('FAST', 'Fastenal'), ('GLCRFT', 'Glass Crafters'), ('MIC', 'Michaels'), ('ADO', 'Adorama')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(choices=[('DOE', 'ShopDOE'), ('AMZ', 'Amazon'), ('BLICK', 'Blick'), ('HD', 'Home Depot'), ('Fl', 'Form Labs'), ('BL', 'Bambu Lab'), ('HL', 'Hobby Lobby'), ('FAST', 'Fastenal'), ('GLCRFT', 'Glass Crafters'), ('MIC', 'Michaels'), ('ADO', 'Adorama')], default=None, max_length=100),
        ),
    ]
