describe('template spec', () => {
  it('passes', () => {
    cy.visit('/')
    cy.get('.addItem > .material-symbols-outlined').click()
    cy.get('#item_id').type('tester123ID{enter}')
    cy.get('#name').type('tester123Name{enter}')
    cy.get('#quantity-makerspace').type('abc123{enter}')
    cy.get('#quantity-backroom').type('abc456{enter')
    cy.get('#min_amount').type('min69{enter}')
    cy.get('#location').type('urmomshouse{enter}')
    cy.get('#purchase_link').type('uwumommy.com')
    cy.get('#Vendor').select(1)
    cy.get('#Category').select(11)
    cy.get('#image_url').type('https://i.pinimg.com/736x/1b/23/07/1b230783cb0d380a4586f386c4cd7e29.jpg')
    cy.get('.submit-button').click()
    cy.wait(1000) // Wait for the element to become visible
    cy.get(':nth-child(2) > [data-v-inspector="components/itemPerCat.vue:3:5"] > .itemHolder >').last().click()
    cy.get('.editbtn').click()
    cy.get('.col2 > input').click()
    cy.get('.col2 > input').type('edited')
    cy.get('#Category').select(20)
    cy.get('#Vendor').select(2)
    cy.get('.detailsStock > .col2').click()
    cy.get('[data-v-inspector="components/extra.vue:84:9"] > [type="number"]').type('{backspace}{backspace}{backspace}1')
    cy.get('[data-v-inspector="components/extra.vue:84:9"] > .input').type('2')
    cy.get('[data-v-inspector="components/extra.vue:84:9"] > .updateBtn').click()
    cy.get('[data-v-inspector="components/extra.vue:95:9"] > [type="number"]').type('{backspace}{backspace}{backspace}1')
    cy.get('[data-v-inspector="components/extra.vue:95:9"] > .input').type('-1')
    cy.get('[data-v-inspector="components/extra.vue:95:9"] > .updateBtn').click()
    cy.get('.detailsPurchase > input').clear()
    cy.get('.detailsPurchase > input').type('gowatchonepiece.com')
    cy.get('.addCurrentDate').click()
    cy.get('.save').click()
    cy.get('.tab1 > .exitbtn').click()

  })
})